services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file: .env
    depends_on:
      - postgres
      - redis
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file: .env
    depends_on:
      - api
      - redis
