import Head from 'next/head';
import {useRouter} from 'next/router';
import {useEffect,useMemo,useState} from 'react';
import Nav from '../../components/Nav';
import Footer from '../../components/Footer';
import {apiFetch,apiJSON,currentUser,readJSON} from '../../lib/api';

const money=value=>Number(value||0).toLocaleString('ru-RU',{maximumFractionDigits:2});
const num=value=>Number(value||0).toLocaleString('ru-RU',{maximumFractionDigits:2});
const when=value=>value?new Date(value).toLocaleString('ru-RU',{day:'2-digit',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
const severityMap={high:{label:'Критический',tone:'critical',color:'#ef4444',rank:4},critical:{label:'Критический',tone:'critical',color:'#ef4444',rank:4},высокий:{label:'Критический',tone:'critical',color:'#ef4444',rank:4},medium:{label:'Важный',tone:'warning',color:'#f59e0b',rank:3},warning:{label:'Важный',tone:'warning',color:'#f59e0b',rank:3},средний:{label:'Важный',tone:'warning',color:'#f59e0b',rank:3},low:{label:'Низкий',tone:'low',color:'#22c55e',rank:2},низкий:{label:'Низкий',tone:'low',color:'#22c55e',rank:2},info:{label:'Информация',tone:'info',color:'#3b82f6',rank:1},информация:{label:'Информация',tone:'info',color:'#3b82f6',rank:1}};
const severityMeta=value=>severityMap[String(value||'info').trim().toLowerCase()]||{label:value||'Информация',tone:'info',color:'#3b82f6',rank:1};
const statusLabel=status=>status==='review_required'?'Нужна проверка':status==='ready'?'Готово':status==='processing'?'Анализируется':status||'Готово';
function scoreCopy(score){if(score>=90)return['Структура сметы выглядит надёжно','Критических структурных ошибок немного. Всё равно проверьте замечания и крупные позиции.'];if(score>=75)return['Смета требует точечных уточнений','Структура читаемая, но отдельные проблемы могут повлиять на стоимость или понимание объёмов.'];if(score>=50)return['Нужна внимательная ручная проверка','Есть заметные проблемы с данными или расчётами. Не утверждайте смету до исправления ключевых замечаний.'];return['Высокий риск ошибочного согласования','Данные неполные или содержат серьёзные несоответствия. Запросите исправленную версию сметы.'];}
function findingAction(finding){const text=`${finding?.title||''} ${finding?.detail||''}`.toLowerCase();if(text.includes('дубл'))return'Уточните, относятся ли позиции к разным этапам или одна внесена повторно.';if(text.includes('единиц'))return'Добавьте единицу измерения и подтвердите расчёт количества, цены и итога.';if(text.includes('итог')||text.includes('сумм')||text.includes('расч'))return'Запросите исправленный арифметический расчёт и сравните его с договором.';if(text.includes('нул')||text.includes('пуст'))return'Заполните отсутствующее значение или исключите строку из итогового бюджета.';if(text.includes('крупн')||text.includes('дорог'))return'Запросите спецификацию, расчёт или предложение поставщика.';return'Уточните исходные данные, внесите исправление и повторно загрузите файл.';}
function extractFindingRows(finding){
  const text=`${finding?.title||''} ${finding?.detail||''}`;
  const rows=[];
  const pattern=/(?:строк(?:а|и|е|у|ой|ах)?|rows?)\s*(?:№|#|:)?\s*(\d+)(?:\s*(?:и|and|,|\/|-)\s*(\d+))?/giu;
  for(const match of text.matchAll(pattern)){
    rows.push(Number(match[1]));
    if(match[2])rows.push(Number(match[2]));
  }
  return [...new Set(rows.filter(Number.isFinite))];
}
function FindingRowEvidence({finding,items}){
  const rowNumbers=extractFindingRows(finding);
  if(!rowNumbers.length)return <div className="sourceRows fileLevel"><div className="sourceRowsTitle"><span>Проверка уровня файла</span><b>Конкретная строка не указана</b></div><p>Это замечание относится ко всему файлу или результату обработки. Оно не является утверждением об ошибке в одной конкретной позиции.</p></div>;
  const rows=rowNumbers.map(rowNumber=>({rowNumber,item:(items||[]).find(item=>Number(item.row)===rowNumber)}));
  return <div className="sourceRows"><div className="sourceRowsTitle"><span>Исходные данные</span><b>{rowNumbers.length>1?'Строки из сметы':'Строка из сметы'}</b></div>{rows.map(({rowNumber,item})=>item?<article className="sourceRowCard" key={rowNumber}><div className="sourceRowHeading"><span>Строка {rowNumber}</span><strong>{item.name||'Без названия'}</strong></div><div className="sourceRowValues"><div><span>Единица</span><b>{item.unit||'Не указана'}</b></div><div><span>Количество</span><b>{num(item.quantity)}</b></div><div><span>Цена</span><b>{money(item.unit_price)} сом</b></div><div><span>Сумма в смете</span><b>{money(item.total)} сом</b></div></div>{Number(item.quantity)>0&&Number(item.unit_price)>0&&<div className="sourceRowFormula"><span>Проверка расчёта</span><code>{num(item.quantity)} × {money(item.unit_price)} = {money(Number(item.quantity)*Number(item.unit_price))} сом</code>{Math.abs(Number(item.total)-(Number(item.quantity)*Number(item.unit_price)))>.01&&<b>Отклонение: {money(Math.abs(Number(item.total)-(Number(item.quantity)*Number(item.unit_price))))} сом · {Number(item.total)<Number(item.quantity)*Number(item.unit_price)?'в смете меньше расчётного':'в смете больше расчётного'}</b>}</div>}</article>:<article className="sourceRowCard missing" key={rowNumber}><div className="sourceRowHeading"><span>Строка {rowNumber}</span><strong>Позиция не распознана</strong></div><p>Номер строки указан в замечании, но эта строка не попала в список распознанных позиций. Откройте исходный Excel или CSV и проверьте её вручную.</p></article>)}</div>;
}
function ScoreGauge({score}){const value=Math.max(0,Math.min(100,Number(score||0)));const radius=66;const circle=2*Math.PI*radius;return <div className="scoreGauge"><svg viewBox="0 0 160 160"><circle className="scoreGaugeTrack" cx="80" cy="80" r={radius}/><circle className="scoreGaugeValue" cx="80" cy="80" r={radius} strokeDasharray={circle} strokeDashoffset={circle-(value/100)*circle}/></svg><div><strong>{value}</strong><span>из 100</span></div></div>;}
function RiskDonut({groups}){const data=[groups.high,groups.medium,groups.low,groups.info];const colors=['#ef4444','#f59e0b','#22c55e','#3b82f6'];const total=data.reduce((sum,item)=>sum+item,0);let cursor=0;const segments=data.map((value,index)=>{const start=cursor;cursor+=total?value/total*360:0;return`${colors[index]} ${start}deg ${cursor}deg`;});const background=total?`conic-gradient(${segments.join(',')})`:'conic-gradient(#e2e8f0 0deg 360deg)';return <div className="riskDonutWrap"><div className="riskDonut" style={{background}}><div><strong>{total}</strong><span>замечаний</span></div></div><div className="riskLegend"><span><i className="critical"/>Критические <b>{groups.high}</b></span><span><i className="warning"/>Важные <b>{groups.medium}</b></span><span><i className="low"/>Низкие <b>{groups.low}</b></span><span><i className="info"/>Информация <b>{groups.info}</b></span></div></div>;}
function BudgetBars({items,total}){const top=[...(items||[])].filter(item=>Number(item.total)>0).sort((a,b)=>Number(b.total)-Number(a.total)).slice(0,6);const max=Math.max(...top.map(item=>Number(item.total||0)),1);if(!top.length)return <div className="reportEmptyMini">Нет распознанных сумм для диаграммы.</div>;return <div className="budgetBars">{top.map((item,index)=>{const share=total>0?Number(item.total||0)/total*100:0;return <div className="budgetBar" key={`${item.row}-${item.name}`}><div className="budgetBarHead"><span><b>{index+1}</b>{item.name||`Строка ${item.row}`}</span><strong>{money(item.total)} сом</strong></div><div className="budgetBarTrack"><i style={{width:`${Math.max(4,Number(item.total||0)/max*100)}%`}}/></div><small>{share.toFixed(1)}% от распознанной суммы</small></div>;})}</div>;}
function FindingCard({finding,index,items}){const meta=severityMeta(finding.severity);return <details className={`findingCard ${meta.tone}`}><summary><span className="findingIndex">{String(index+1).padStart(2,'0')}</span><span className="findingSummaryText"><b>{finding.title||'Замечание'}</b><small>{finding.detail||'Откройте карточку, чтобы увидеть подробности.'}</small></span><span className={`severityBadge ${meta.tone}`}><i/>{meta.label}</span><span className="findingChevron">⌄</span></summary><div className="findingDetails"><FindingRowEvidence finding={finding} items={items}/><div className="findingExplanationGrid"><div><span className="detailLabel">Что обнаружено</span><p>{finding.detail||'Подробное описание отсутствует.'}</p></div><div><span className="detailLabel">Почему это может быть проблемой</span><p>{meta.rank>=4?'Расхождение может повлиять на итоговую стоимость или привести к неверному согласованию. Сначала сравните вывод с показанной исходной строкой.':meta.rank===3?'Позиция требует уточнения. Система показывает сигнал для проверки, а окончательное решение принимает пользователь после сверки с исходной строкой.':'Это информационный сигнал для повышения прозрачности данных. Он не обязательно означает ошибку.'}</p></div><div className="findingAction"><span className="detailLabel">Как проверить и исправить</span><p>{findingAction(finding)}</p></div></div></div></details>;}
export default function ReportDetail(){
  const {query}=useRouter();
  const [estimate,setEstimate]=useState(null);const [ai,setAi]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [activeTab,setActiveTab]=useState('overview');const [severityFilter,setSeverityFilter]=useState('all');const [findingSearch,setFindingSearch]=useState('');const [itemSearch,setItemSearch]=useState('');const [downloadLoading,setDownloadLoading]=useState(false);const [deleting,setDeleting]=useState(false);const [printing,setPrinting]=useState(false);
  async function load(){if(!query.id)return;setLoading(true);setError('');try{if(!await currentUser())throw new Error('Сессия истекла. Войдите снова.');const result=await apiJSON(`/v1/estimates/${query.id}`);if(!result.response.ok)throw new Error(result.data.error||'Не удалось загрузить отчёт.');setEstimate(result.data);const aiResult=await apiJSON(`/v1/ai/estimate-summary/${query.id}`);if(aiResult.response.ok)setAi(aiResult.data);}catch(err){setError(err.message||'Не удалось загрузить отчёт.');}finally{setLoading(false);}}
  async function download(){if(!estimate)return;setDownloadLoading(true);try{const response=await apiFetch(`/v1/estimates/${estimate.id}/report`);if(!response.ok){const data=await readJSON(response);throw new Error(data.error||'Не удалось скачать отчёт.');}const url=URL.createObjectURL(await response.blob());const link=document.createElement('a');link.href=url;link.download=`${estimate.id}_report.txt`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);}catch(err){setError(err.message||'Не удалось скачать отчёт.');}finally{setDownloadLoading(false);}}
  async function removeEstimate(){if(!estimate||deleting)return;const confirmed=window.confirm('Удалить эту смету, позиции и отчёт? Это действие нельзя отменить.');if(!confirmed)return;setDeleting(true);setError('');try{const response=await apiFetch(`/v1/estimates/${estimate.id}`,{method:'DELETE'});if(!response.ok){const data=await readJSON(response);throw new Error(data.error||'Не удалось удалить смету.');}window.location.href='/reports?deleted=1';}catch(err){setError(err.message||'Не удалось удалить смету.');setDeleting(false);}}
  useEffect(()=>{load();},[query.id]);useEffect(()=>{const finish=()=>setPrinting(false);window.addEventListener('afterprint',finish);return()=>window.removeEventListener('afterprint',finish);},[]);
  function printReport(){setPrinting(true);setTimeout(()=>window.print(),120);}
  const findings=estimate?.findings||[];const items=estimate?.items||[];
  const groups=useMemo(()=>findings.reduce((acc,finding)=>{const meta=severityMeta(finding.severity);if(meta.tone==='critical')acc.high++;else if(meta.tone==='warning')acc.medium++;else if(meta.tone==='low')acc.low++;else acc.info++;return acc;},{high:0,medium:0,low:0,info:0}),[findings]);
  const filteredFindings=useMemo(()=>findings.map((finding,index)=>({finding,index,meta:severityMeta(finding.severity)})).filter(entry=>severityFilter==='all'||entry.meta.tone===severityFilter).filter(entry=>`${entry.finding.title||''} ${entry.finding.detail||''}`.toLowerCase().includes(findingSearch.trim().toLowerCase())).sort((a,b)=>b.meta.rank-a.meta.rank),[findings,severityFilter,findingSearch]);
  const filteredItems=useMemo(()=>items.filter(item=>`${item.name||''} ${item.unit||''} ${item.row||''}`.toLowerCase().includes(itemSearch.trim().toLowerCase())),[items,itemSearch]);
  const [scoreTitle,scoreText]=scoreCopy(estimate?.score||0);const highestRisk=groups.high?'Высокий':groups.medium?'Средний':ai?.risk_level||'Низкий';const topShare=items.length&&estimate?.total_amount?Math.max(...items.map(item=>Number(item.total||0)))/Number(estimate.total_amount||1)*100:0;const zeroRows=items.filter(item=>Number(item.quantity)<=0||Number(item.unit_price)<=0||Number(item.total)<=0).length;
  const tabs=[['overview','Обзор'],['findings',`Проблемы · ${findings.length}`],['actions','Рекомендации'],['items',`Позиции · ${items.length}`]];
  return <main className="page reportPage"><Head><title>{estimate?.file_name?`${estimate.file_name} — отчёт SmetaCheck`:'Отчёт SmetaCheck'}</title></Head><Nav/><section className="reportShell">
    {loading&&<div className="reportLoading"><span className="loadingOrb"/><h1>Формируем аналитический отчёт</h1><p>Собираем показатели, риски и рекомендации по смете.</p></div>}
    {!loading&&error&&<div className="reportError"><span>!</span><h1>Не удалось открыть отчёт</h1><p>{error}</p><div className="buttonRow"><button className="btn" onClick={load}>Повторить</button><a className="btn secondary" href="/reports">К списку отчётов</a></div></div>}
    {!loading&&!error&&estimate&&<>
      <header className="reportHeaderModern"><div className="reportBreadcrumbs"><a href="/reports">Отчёты</a><span>/</span><b>{estimate.file_name}</b></div><div className="reportHeaderGrid"><div><div className="reportStatusLine"><span className="liveDot"/>{statusLabel(estimate.status)}<span>•</span>{when(estimate.uploaded_at)}</div><h1>{estimate.file_name}</h1><p>Интерактивный анализ структуры, стоимости и рисков. Нажмите на проблему, чтобы увидеть подробности и действие.</p></div><div className="reportHeaderActions"><button className="btn" onClick={printReport} disabled={deleting}>Сохранить PDF</button><button className="btn secondary" onClick={download} disabled={downloadLoading||deleting}>{downloadLoading?'Скачиваем…':'Скачать TXT'}</button><a className="btn secondary" href="/reports">Все отчёты</a><button className="btn secondary dangerButton" type="button" onClick={removeEstimate} disabled={deleting}>{deleting?'Удаляем…':'Удалить смету'}</button></div></div></header>
      <section className="reportHeroGrid"><article className="reportScoreCard"><ScoreGauge score={estimate.score}/><div><span className="sectionKicker">Итоговая оценка</span><h2>{scoreTitle}</h2><p>{scoreText}</p><div className="scoreSignals"><span><i className="critical"/>{groups.high} критических</span><span><i className="warning"/>{groups.medium} важных</span></div></div></article><article className="reportQuickFacts"><div><span>Общая сумма</span><strong>{money(estimate.total_amount)} <small>сом</small></strong></div><div><span>Распознано позиций</span><strong>{estimate.items_count||items.length}</strong></div><div><span>Уровень риска</span><strong className="riskText">{highestRisk}</strong></div><div><span>Крупнейшая позиция</span><strong>{topShare.toFixed(1)}<small>% бюджета</small></strong></div></article></section>
      <nav className="reportTabs">{tabs.map(([key,label])=><button key={key} className={activeTab===key?'active':''} onClick={()=>setActiveTab(key)}>{label}</button>)}</nav>
      {(activeTab==='overview'||printing)&&<section className="reportTabPanel"><div className="reportDashboardGrid">
        <article className="analyticsCard analyticsWide"><div className="analyticsHeader"><div><span className="sectionKicker">AI-резюме</span><h2>Что важно знать сейчас</h2></div><span className={`analysisSource ${ai?.analysis_source==='rules'?'rules':'ai'}`}>{ai?.analysis_source==='rules'?'Проверяемые правила':'AI + правила'}</span></div>{ai?<><p className="executiveBrief">{ai.executive_brief}</p>{ai.warning&&<div className="reportWarning">{ai.warning}</div>}<div className="insightGrid"><div><span>Качество данных</span><b>{ai.data_quality_score}/100</b></div><div><span>Риск анализа</span><b>{ai.risk_level}</b></div><div><span>Источник</span><b>{ai.provider||ai.analysis_source||'rules'}</b></div></div></>:<p className="executiveBrief">Основные показатели рассчитаны из распознанных данных сметы.</p>}</article>
        <article className="analyticsCard"><div className="analyticsHeader"><div><span className="sectionKicker">Распределение рисков</span><h2>Замечания по уровню</h2></div></div><RiskDonut groups={groups}/></article>
        <article className="analyticsCard analyticsWide"><div className="analyticsHeader"><div><span className="sectionKicker">Концентрация бюджета</span><h2>Самые дорогие позиции</h2></div><span className="metricHint">Топ-6</span></div><BudgetBars items={items} total={Number(estimate.total_amount||0)}/></article>
        <article className="analyticsCard"><div className="analyticsHeader"><div><span className="sectionKicker">Качество данных</span><h2>Быстрые сигналы</h2></div></div><div className="qualitySignals"><div><span>Строк с нулевыми значениями</span><b>{zeroRows}</b></div><div><span>Всего замечаний</span><b>{findings.length}</b></div><div><span>Покрытие анализа</span><b>{items.length?100:0}%</b></div><div><span>Размер файла</span><b>{estimate.file_size?`${(estimate.file_size/1024).toFixed(1)} КБ`:'—'}</b></div></div></article>
      </div></section>}
      {(activeTab==='findings'||printing)&&<section className="reportTabPanel">
        <div className="sectionTitleRow"><div><span className="sectionKicker">Проблемы и риски</span><h2>Что проверить до согласования</h2><p>Раскройте карточку, чтобы увидеть влияние проблемы и рекомендуемое действие.</p></div><div className="findingSearch"><input value={findingSearch} onChange={event=>setFindingSearch(event.target.value)} placeholder="Поиск по проблемам…"/></div></div>
        <div className="severityFilters"><button className={severityFilter==='all'?'active':''} onClick={()=>setSeverityFilter('all')}>Все <b>{findings.length}</b></button><button className={severityFilter==='critical'?'active critical':''} onClick={()=>setSeverityFilter('critical')}>Критические <b>{groups.high}</b></button><button className={severityFilter==='warning'?'active warning':''} onClick={()=>setSeverityFilter('warning')}>Важные <b>{groups.medium}</b></button><button className={severityFilter==='low'?'active low':''} onClick={()=>setSeverityFilter('low')}>Низкие <b>{groups.low}</b></button><button className={severityFilter==='info'?'active info':''} onClick={()=>setSeverityFilter('info')}>Информация <b>{groups.info}</b></button></div>
        <div className="findingListModern">{filteredFindings.length?filteredFindings.map(entry=><FindingCard key={`${entry.index}-${entry.finding.title}`} finding={entry.finding} index={entry.index} items={items}/>):<div className="reportEmptyState"><span>✓</span><h3>По выбранному фильтру проблем нет</h3><p>Измените фильтр или поисковый запрос.</p></div>}</div>
      </section>}
      {(activeTab==='actions'||printing)&&<section className="reportTabPanel">
        <div className="sectionTitleRow"><div><span className="sectionKicker">План действий</span><h2>Как довести смету до согласования</h2><p>Приоритетные шаги сформированы на основе найденных проблем.</p></div></div>
        <div className="actionBoard"><article className="actionColumn priority"><div className="actionColumnHeader"><span>01</span><div><b>Сделать в первую очередь</b><small>Критические исправления</small></div></div><ol>{(ai?.priority_actions?.length?ai.priority_actions:['Исправить критические и важные замечания.','Проверить крупные позиции и арифметические расхождения.','Повторно загрузить исправленную смету.']).map(item=><li key={item}>{item}</li>)}</ol></article><article className="actionColumn"><div className="actionColumnHeader"><span>02</span><div><b>Вопросы подрядчику</b><small>Что нужно подтвердить</small></div></div><ul>{(ai?.questions?.length?ai.questions:['Совпадает ли итоговая сумма с договором и объёмом работ?']).map(item=><li key={item}>{item}</li>)}</ul></article><article className="actionColumn"><div className="actionColumnHeader"><span>03</span><div><b>Финансовые сигналы</b><small>Позиции для ручной проверки</small></div></div><ul>{(ai?.cost_flags?.length?ai.cost_flags:[`Проверить крупнейшую позицию — ${topShare.toFixed(1)}% общей суммы.`]).map(item=><li key={item}>{item}</li>)}</ul></article></div>
        <article className="finalRecommendation"><span className="sectionKicker">Итоговая рекомендация</span><h2>{ai?.recommendation||'Исправьте замечания, подтвердите крупные затраты и повторно проверьте обновлённую смету.'}</h2><a className="btn" href="/upload">Загрузить исправленную версию</a></article>
      </section>}
      {(activeTab==='items'||printing)&&<section className="reportTabPanel">
        <div className="sectionTitleRow"><div><span className="sectionKicker">Позиции сметы</span><h2>Распознанные строки и стоимость</h2><p>Используйте поиск, чтобы быстро найти материал, работу или строку.</p></div><div className="findingSearch"><input value={itemSearch} onChange={event=>setItemSearch(event.target.value)} placeholder="Материал, работа или строка…"/></div></div>
        <div className="itemsSummary"><span>Показано <b>{filteredItems.length}</b> из {items.length}</span><span>Итог <b>{money(estimate.total_amount)} сом</b></span></div>
        <div className="modernTableWrap"><table className="modernTable"><thead><tr><th>Строка</th><th>Позиция</th><th>Ед.</th><th>Количество</th><th>Цена</th><th>Сумма</th><th>Доля</th></tr></thead><tbody>{filteredItems.map(item=>{const share=estimate.total_amount?Number(item.total||0)/Number(estimate.total_amount)*100:0;return <tr key={`${item.row}-${item.name}`}><td><span className="rowPill">{item.row}</span></td><td><b>{item.name||'Без названия'}</b></td><td>{item.unit||'—'}</td><td>{num(item.quantity)}</td><td>{money(item.unit_price)}</td><td><strong>{money(item.total)}</strong></td><td><div className="shareCell"><i style={{width:`${Math.min(100,share)}%`}}/><span>{share.toFixed(1)}%</span></div></td></tr>})}</tbody></table>
        {!filteredItems.length&&<div className="reportEmptyState"><span>⌕</span><h3>Позиции не найдены</h3><p>Измените поисковый запрос.</p></div>}</div>
      </section>}
    </>}
  </section><Footer/></main>;
}
